.TH ARPTABLES-LEGACY-SAVE 8 "May 09, 2018" "" ""
.\"
.\" Man page written by Alberto Molina Coballes <alb.molina@gmail.com>
.\" It is based on the arptables-save man page.
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 2 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\"
.SH NAME
ebtables-legacy-save \- Dump ebtables rules to stdout
.SH SYNOPSIS
.BR "ebtables-legacy-save "
.br
.SH DESCRIPTION
.PP
.B ebtables-legacy-save
is used to dump the contents of an Ethernet bridge frame Table in
easily parseable format to STDOUT. Use I/O-redirection provided by
your shell to write to a file.
.SH BUGS
None known as of ebtables-2.0.10-4 release
.SH AUTHOR
Bart De Schuymer <bdschuym@pandora.be>
.SH SEE ALSO
.BR ebtables-legacy-restore "(8), " ebtables-legacy "(8) "
